name: Build
on: [workflow_call]
jobs:
  build:
    name: Build > Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install project dependencies
        run: npm install

      - name: Take build
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
